name: Deploy to IIS

on:
  push:
    branches:
      - production

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Publish
      run: dotnet publish -c Release -o publish

    - name: Copy Files to IIS
      run: xcopy /E /I /Y publish C:\inetpub\wwwroot\OFMSAPI

    - name: Restart IIS
      run: iisreset /restart
