name: Deploy to IIS

on:
  push:
    branches:
      - production

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Publish
      run: dotnet publish -c Release -o publish

    - name: Stop App Pool
      run: C:\Windows\System32\inetsrv\appcmd stop apppool /apppool.name:"OFMSAPIAppPool"

    - name: Copy Files to IIS
      run: robocopy publish C:\inetpub\wwwroot\OFMSAPI /E /IS /IT /IM

    - name: Start App Pool
      run: C:\Windows\System32\inetsrv\appcmd start apppool /apppool.name:"OFMSAPIAppPool"
